name: media-vault
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/bazarr/config:/config
      - $DATA/movies:/movies
      - $DATA/shows:/shows
    ports:
      - 6767:6767

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/sonarr/data:/config
      - $DATA/tv:/tv
      - $DATA/downloads:/downloads
    ports:
      - 8989:8989

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=$JELLYFIN
    volumes:
      - $DATA/jellyfin/library:/config
      - $DATA/downloads:/downloads
      - $DATA/movies:/movies
      - $DATA/shows:/shows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - $DATA/qbittorrent/appdata:/config
      - $DATA/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/radarr/data:/config
      - $DATA/movies:/movies
      - $DATA/downloads:/downloads
    ports:
      - 7878:7878

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/prowlarr/data:/config
    ports:
      - 9696:9696

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    volumes:
      - $DATA/flaresolverr/data:/config
    ports:
      - 8191:8191

networks:
  default:
    driver: bridge
