---
name: flaresolverr
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - streama
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    volumes:
      - $DATA/flaresolverr/data:/config
    ports:
      - 8191:8191

networks:
  streama:
    external: true
