---
name: radarr
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - streama
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DATA/radarr/data:/config
      - $DATA/movies:/movies
      - $DATA/downloads:/downloads
    ports:
      - 7878:7878

networks:
  streama:
    external: true
